### ISSUE TITLE
Angular 12 build fails with version 2.0.2 and node v12.14.1

### ISSUE THREAD

**Issue by poman31** [HdrHistogram/HdrHistogramJS#42]
An angular 12 project requires  'angular-devkit/build-angular' package which has dependency with 'piscina' and 'piscina' depends on 'hdr-histogram-js'.  Version 2.0.2 of this library when combined with node 12.14.1 produces this error on both windows and linux

An unhandled exception occurred: Unexpected token 'export'
See "/tmp/ng-xl90En/angular-errors.log" for further details.

[error]                       angular-test\node_modules\@assemblyscript\loader\index.js:355
export async function instantiate(source, imports = {}) {
^^^^^^

SyntaxError: Unexpected token 'export'
    at compileFunction (<anonymous>)
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (angular-test\node_modules\hdr-histogram-js\dist\wasm\index.js:20:18)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)

I am required to support node 12, so I had to downgrade this package to 2.0.1 to get my builds working

node - v12.14.1
npm - v6.13.4
@angular-devkit/build-angular - 12.2.14
@angular/cli - 12.2.14

**Comment by leeran88** [comment]
Happens to me also when running tests, not related to Angular

**Comment by alexvictoor** [comment]
Sorry folks for the trouble!
I did forget that @assemblyscript/loader requires nodejs@14. I have published a fix, hdr-histogram-js@2.0.3. Let me know if the problem is solved on your side.
I will republish hdr-histogram-js@2.0.2 as hdr-histogram-js@3.0.0 to avoid any nodejs compatibility issue.

**Comment by karanr69** [comment]
thanx for your quick fix

**Comment by leeran88** [comment]
@alexvictoor thanks for fixing it so quickly!
`hdr-histogram-js@2.0.3` Is working for me 👍
